### ISSUE TITLE
Could you include offline storage for github issues?

### ISSUE THREAD

**Issue by lukasoppermann** [ShaharHD/BugHub#2]

**Comment by ShaharHD** [comment]
I’m not the original maintainer of the code, I’ve just patched it a bit to make it work better.
(just like the comment window).

Adding an offline ability will require to make sure to be able to save all the comments and issues data, and then sync them.

I know that when you have big issues or a large number of them, it tends to get slower and slower …

I’ll look at it next week, and will update this issue.

**Comment by lukasoppermann** [comment]
Hey, thanks for taking this on. I know that you are nit the original maintainer but you have the mist active branch. :+1: 

For a start making an inactive "view" mode when online would help already. Of course it would be great to allow for offline editing. Thanks for looking into it.

**Comment by ShaharHD** [comment]
FYI ... I've been using this `https://www.realartists.com/index.html`
